# Generated by Django 5.2.15 on 2026-06-09 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('hero', 'Hero / Background'), ('testimonial', 'Testimonial'), ('property', 'Property'), ('team', 'Team'), ('general', 'General')], default='general', max_length=50)),
                ('video_file', models.FileField(blank=True, help_text='Upload an .mp4 file', upload_to='videos/')),
                ('video_url', models.URLField(blank=True, help_text='Or paste a YouTube / Vimeo / direct video URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ForeignKey(blank=True, help_text='Optional preview thumbnail', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.rgpimage')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-updated_at'],
            },
        ),
    ]
