# Generated by Django 5.2.12 on 2026-06-29 10:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', wagtail.fields.RichTextField(blank=True, help_text='Content for the Privacy Policy page.')),
                ('collection_notice', wagtail.fields.RichTextField(blank=True, help_text='Content for the Collection Notice page.')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Legal Pages',
            },
        ),
    ]
