# Generated by Django 5.2.12 on 2026-04-07 11:36

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='badge',
            field=models.CharField(blank=True, help_text='Optional badge shown on property card.', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='days_on_market',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_category',
            field=models.CharField(choices=[('for-sale', 'For Sale'), ('sold', 'Sold'), ('for-rent', 'For Rent')], default='for-sale', help_text='Used by homepage listing filters (For Sale / Sold / For Rent).', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='map_embed_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='min_lease',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='property',
            name='sold_date_label',
            field=models.CharField(blank=True, help_text='e.g. 5 weeks ago', max_length=80),
        ),
        migrations.AddField(
            model_name='property',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='video_thumbnail_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='video_tour_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('sold', 'Sold'), ('pending', 'Pending')], default='for_sale', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyDetailRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=500)),
                ('property', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_rows', to='properties.property')),
            ],
            options={
                'verbose_name': 'Detail Row',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyNearbyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('distance', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('shopping', 'Shopping'), ('airport', 'Airport'), ('dining', 'Dining'), ('golf', 'Golf'), ('beach', 'Beach'), ('school', 'School'), ('hospital', 'Hospital')], default='shopping', max_length=20)),
                ('property', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_locations', to='properties.property')),
            ],
            options={
                'verbose_name': 'Nearby Location',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
