# Generated by Django 5.2.12 on 2026-04-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('properties', '0002_property_badge_property_days_on_market_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.rgpimage'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='url',
            field=models.CharField(blank=True, help_text='Optional fallback URL. Used only if no image is selected above.', max_length=500),
        ),
    ]
