# Generated by Django 5.2.12 on 2026-04-07 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('properties', '0003_propertyimage_image_alter_propertyimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='card_image',
            field=models.ForeignKey(blank=True, help_text='Single image used on listing cards.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.rgpimage'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
