# Generated by Django 5.2.12 on 2026-06-10 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('properties', '0005_populate_property_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioShowcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('location', models.CharField(help_text='e.g. Forest Lake, Brisbane QLD', max_length=200)),
                ('price', models.CharField(help_text='e.g. $1.2M, $850,000, Contact Agent', max_length=100)),
                ('status', models.CharField(default='For Sale', help_text='e.g. For Sale, Sold, For Rent', max_length=80)),
                ('beds', models.PositiveSmallIntegerField(default=0)),
                ('baths', models.PositiveSmallIntegerField(default=0)),
                ('area', models.CharField(blank=True, help_text='e.g. 2,400', max_length=50)),
                ('property_slug', models.SlugField(blank=True, help_text="Slug of a property listing to link to (e.g. 'forest-lake-villa'). Leave blank if no listing exists.")),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order in the showcase.')),
                ('background_image', models.ForeignKey(blank=True, help_text='Full-screen parallax background image shown behind the section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.rgpimage')),
                ('thumbnail', models.ForeignKey(blank=True, help_text='Card thumbnail image. Falls back to background image if not set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.rgpimage')),
            ],
            options={
                'verbose_name': 'Portfolio Showcase Item',
                'verbose_name_plural': 'Portfolio Showcase Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
