# Generated by Django 5.2.12 on 2026-06-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_portfolioshowcaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioshowcaseitem',
            name='vault_property_id',
            field=models.CharField(blank=True, default='', help_text='VaultRE property ID (find it in the property URL: /properties/<id>). When set, title/price/photos/beds/baths auto-fill from VaultRE.', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolioshowcaseitem',
            name='property_slug',
            field=models.SlugField(blank=True, help_text='Slug of a property listing to link to. Leave blank — auto-set from vault_property_id if provided.'),
        ),
    ]
