# Generated by Django 5.2.12 on 2026-06-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_add_vault_property_id_to_showcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
        migrations.DeleteModel(
            name='PropertyAgent',
        ),
    ]
