# Generated by Django 5.2.12 on 2026-06-29 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_remove_propertyagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioshowcaseitem',
            name='local_property',
            field=models.ForeignKey(blank=True, help_text='Local property to link. When set, title/price/beds/baths auto-fill from the local listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='properties.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='show_in_portfolio',
            field=models.BooleanField(default=False, help_text='Show this property in the homepage Portfolio Showcase section.'),
        ),
        migrations.AddField(
            model_name='property',
            name='show_on_home_prime',
            field=models.BooleanField(default=False, help_text='Show this property in the homepage Prime Listing section.'),
        ),
        migrations.AlterField(
            model_name='portfolioshowcaseitem',
            name='property_slug',
            field=models.SlugField(blank=True, help_text='Slug of a property listing to link to. Leave blank — auto-set from vault_property_id or local_property if provided.'),
        ),
        migrations.AlterField(
            model_name='portfolioshowcaseitem',
            name='vault_property_id',
            field=models.CharField(blank=True, default='', help_text='VaultRE property ID. When set, title/price/photos/beds/baths auto-fill from VaultRE.', max_length=50),
        ),
    ]
