# Generated by Django 5.2.12 on 2026-05-21 05:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("wagtaildocs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextTestimonial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(help_text="Unique slug for this testimonial record.", max_length=200, unique=True)),
                ("client_name", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, default="", help_text="e.g. Brisbane, QLD", max_length=200)),
                ("quote", models.TextField(help_text="Main testimonial copy.")),
                ("rating", models.PositiveSmallIntegerField(default=5, help_text="1 to 5 stars.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ("order", models.PositiveIntegerField(default=0, help_text="Lower numbers appear first.")),
                ("is_active", models.BooleanField(default=True, help_text="Only active testimonials are returned by the API.")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_image", models.ForeignKey(blank=True, help_text="Optional client avatar from media library.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="core.rgpimage")),
            ],
            options={
                "verbose_name": "Text Testimonial",
                "verbose_name_plural": "Text Testimonials",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="VideoTestimonial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(help_text="Unique slug for this testimonial record.", max_length=200, unique=True)),
                ("name", models.CharField(help_text="Client name shown on card.", max_length=200)),
                ("kicker", models.CharField(blank=True, default="", help_text="e.g. SUNNYBANK · SOLD", max_length=200)),
                ("video_url", models.CharField(blank=True, default="", help_text="Path relative to front public/ (e.g. vids/x.mp4) or full URL.", max_length=500)),
                ("tint", models.CharField(choices=[("gold", "Gold"), ("amber", "Amber"), ("crimson", "Crimson")], default="gold", max_length=20)),
                ("order", models.PositiveIntegerField(default=0, help_text="Lower numbers appear first.")),
                ("is_active", models.BooleanField(default=True, help_text="Only active testimonials are sent to the frontend.")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("poster_image", models.ForeignKey(blank=True, help_text="Thumbnail image from media library.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="core.rgpimage")),
                ("video_file", models.ForeignKey(blank=True, help_text="Optional uploaded file. Used when video URL is empty.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="wagtaildocs.document")),
            ],
            options={
                "verbose_name": "Video Testimonial",
                "verbose_name_plural": "Video Testimonials",
                "ordering": ("order", "id"),
            },
        ),
    ]
