# Generated by Django 5.2.12 on 2026-06-09 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique slug for this record.', max_length=200, unique=True)),
                ('kicker', models.CharField(default='★★★★★', help_text='Shown above the title. e.g. "★★★★★" or "SUNNYBANK · SOLD"', max_length=200)),
                ('title_line_1', models.CharField(help_text='First line of the slide heading.', max_length=200)),
                ('title_line_2', models.CharField(blank=True, default='', help_text='Second line (optional).', max_length=200)),
                ('title_line_3', models.CharField(blank=True, default='', help_text='Third line (optional).', max_length=200)),
                ('quote', models.TextField(help_text='Body text displayed on the slide.')),
                ('attribution', models.CharField(blank=True, default='', help_text='Attribution line shown below the quote. e.g. "— James & Priya Hartwell"', max_length=200)),
                ('link_url', models.CharField(blank=True, default='', help_text='If set the attribution becomes a clickable link.', max_length=500)),
                ('image_url', models.CharField(blank=True, default='images/ps1 (1).jpg', help_text='Fallback image path relative to public/ or full URL.', max_length=500)),
                ('theme', models.CharField(choices=[('theme-1', 'Theme 1'), ('theme-2', 'Theme 2'), ('theme-3', 'Theme 3'), ('theme-4', 'Theme 4'), ('theme-5', 'Theme 5'), ('theme-6', 'Theme 6'), ('theme-7', 'Theme 7'), ('theme-8', 'Theme 8'), ('theme-9', 'Theme 9'), ('theme-10', 'Theme 10')], default='theme-1', help_text='Colour theme applied while this slide is active.', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active records are sent to the frontend.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, help_text='Slide image from media library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.rgpimage')),
            ],
            options={
                'verbose_name': 'Featured Testimonial',
                'verbose_name_plural': 'Featured Testimonials',
                'ordering': ('order', 'id'),
            },
        ),
    ]
