# Generated by Django 5.2.12 on 2026-05-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgp_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='address_buyer_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='address_buyer_2_if_different_to_buyer_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='are_you_happy_for_us_to_store_your_information_in_our_database',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='balance_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='building_pest_if_yes_how_many_days',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='buyer_1_full_legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='buyer_2_full_legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='do_you_have_any_other_conditions_for_purchase',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='email_buyer_1',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='email_buyer_2',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='finance_if_yes_how_many_days',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='if_yes_please_state_brief_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='initial_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='phone_buyer_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='phone_buyer_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='property_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='solicitor_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='will_your_offer_be_subject_to_building_pest',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='expressionofinterestsubmission',
            name='will_your_offer_be_subject_to_finance',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
