# Generated by Django 5.2.12 on 2026-06-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgp_forms', '0004_clear_legacy_eoi_message_blob'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyEnquirySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('property_id', models.CharField(blank=True, max_length=200)),
                ('property_title', models.CharField(blank=True, max_length=300)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Property Enquiry',
                'verbose_name_plural': 'Property Enquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
