# Generated by Django 5.2.12 on 2026-06-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgp_forms', '0005_propertyenquirysubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyenquirysubmission',
            name='agent_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
