# Generated by Django 5.2.12 on 2026-04-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line_1', models.CharField(default='Your [gold]Dream[/gold] Home', help_text='First line of the hero title. Use [gold]…[/gold] or [amber]…[/amber] for accent colours.', max_length=200)),
                ('title_line_2', models.CharField(default='[amber]Perfectly[/amber] Delivered', help_text='Second line of the hero title.', max_length=200)),
                ('subtitle', models.TextField(default='350+ premium properties delivered — luxury villas, penthouses & exclusive estates crafted for those who demand the extraordinary.')),
                ('cta_label', models.CharField(default='Explore Properties', max_length=100)),
                ('cta_href', models.CharField(default='/properties', max_length=200)),
                ('background_image_url', models.CharField(default='images/hero-rpg-brisbane.jpg', help_text='Path relative to the Vite public directory, or a full URL.', max_length=500)),
                ('background_poster_url', models.CharField(blank=True, default='', help_text='Optional video poster image URL.', max_length=500)),
                ('background_video_url', models.CharField(blank=True, default='vids/hero-rgp.mp4', help_text='Path relative to the Vite public directory, or a full URL.', max_length=500)),
                ('show_video', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Hero Content',
                'verbose_name_plural': 'Home Hero Content',
            },
        ),
    ]
