# Generated by Django 5.2.12 on 2026-04-07 09:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 9), ('intro', 16), ('property_listing', 20), ('services', 39), ('video_testimonials', 50), ('portfolio', 61)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Your [gold]Dream[/gold] Home', 'help_text': 'Use [gold]…[/gold] or [amber]…[/amber] for accent colour'}), 1: ('wagtail.blocks.CharBlock', (), {'default': '[amber]Perfectly[/amber] Delivered'}), 2: ('wagtail.blocks.TextBlock', (), {'default': '350+ premium properties delivered — luxury villas, penthouses & exclusive estates crafted for those who demand the extraordinary.'}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /properties) or full URL', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'images/hero-rpg-brisbane.jpg', 'help_text': 'Path relative to public/ folder or full URL', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'vids/hero-rgp.mp4', 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 1), ('subtitle', 2), ('cta', 5), ('background_image_url', 6), ('background_video_url', 7), ('background_poster_url', 3), ('show_video', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'About the Founder'}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Building Wealth'}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Through Property,'}), 13: ('wagtail.blocks.CharBlock', (), {'default': '— Rahul Singh'}), 14: ('wagtail.blocks.TextBlock', (), {'default': 'Real Gold Properties is a vision turned reality — a private equity approach to multi-family real estate. Founded by Rahul Singh, we focus on disciplined acquisitions that deliver consistent returns.'}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'images/rahul-singh.jpg', 'help_text': 'Path relative to public/ folder or full URL'}), 16: ('wagtail.blocks.StructBlock', [[('label', 10), ('headline_line1', 11), ('headline_line2', 12), ('founder_name', 13), ('body', 14), ('primary_cta', 5), ('secondary_cta', 5), ('image_url', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Our Listings'}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Available Properties'}), 19: ('wagtail.blocks.TextBlock', (), {'default': 'Explore our current listings across South-East Queensland.', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('eyebrow', 17), ('heading', 18), ('subtitle', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'How Can We Help You?'}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'What Are You'}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'Looking For?'}), 24: ('wagtail.blocks.TextBlock', (), {'default': "Whether you're buying, selling, or renting — we're here to make your real estate journey seamless and rewarding."}), 25: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('buy', 'Buy'), ('sell', 'Sell'), ('rent', 'Rent')]}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'Advisory'}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'Buyer Support'}), 28: ('wagtail.blocks.CharBlock', (), {'default': 'And Guidance'}), 29: ('wagtail.blocks.TextBlock', (), {}), 30: ('wagtail.blocks.CharBlock', (), {}), 31: ('wagtail.blocks.ListBlock', (30,), {'help_text': 'One feature per row'}), 32: ('wagtail.blocks.CharBlock', (), {'default': 'Speak With Us'}), 33: ('wagtail.blocks.StructBlock', [[('theme', 25), ('headline', 26), ('title', 27), ('subtitle', 28), ('description', 29), ('features', 31), ('cta_label', 32)]], {}), 34: ('wagtail.blocks.ListBlock', (33,), {}), 35: ('wagtail.blocks.CharBlock', (), {'default': 'Need Guidance?'}), 36: ('wagtail.blocks.CharBlock', (), {'default': 'Not Sure Where to'}), 37: ('wagtail.blocks.CharBlock', (), {'default': 'Start?'}), 38: ('wagtail.blocks.TextBlock', (), {'default': 'Our experienced advisors are here to understand your needs and guide you through every step of your real estate journey.'}), 39: ('wagtail.blocks.StructBlock', [[('header_eyebrow', 21), ('header_title', 22), ('header_title_em', 23), ('header_subtitle', 24), ('services', 34), ('cta_eyebrow', 35), ('cta_title', 36), ('cta_title_em', 37), ('cta_text', 38), ('cta_primary', 5), ('cta_secondary', 5)]], {}), 40: ('wagtail.blocks.CharBlock', (), {'default': 'Testimonials'}), 41: ('wagtail.blocks.CharBlock', (), {'default': 'What Our'}), 42: ('wagtail.blocks.CharBlock', (), {'default': 'Clients Say'}), 43: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. SUNNYBANK · SOLD'}), 44: ('wagtail.blocks.CharBlock', (), {'help_text': 'Client name shown on the card'}), 45: ('wagtail.blocks.CharBlock', (), {'help_text': 'Path relative to public/ or full URL'}), 46: ('wagtail.blocks.CharBlock', (), {'help_text': 'Thumbnail image URL'}), 47: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('amber', 'Amber'), ('crimson', 'Crimson')]}), 48: ('wagtail.blocks.StructBlock', [[('kicker', 43), ('name', 44), ('video_url', 45), ('poster_url', 46), ('tint', 47)]], {}), 49: ('wagtail.blocks.ListBlock', (48,), {}), 50: ('wagtail.blocks.StructBlock', [[('section_label', 40), ('heading', 41), ('heading_em', 42), ('items', 49)]], {}), 51: ('wagtail.blocks.CharBlock', (), {'default': 'REAL GOLD PROPERTIES'}), 52: ('wagtail.blocks.CharBlock', (), {'default': 'Featured'}), 53: ('wagtail.blocks.CharBlock', (), {'default': 'Properties'}), 54: ('wagtail.blocks.TextBlock', (), {'default': "Handpicked residences across Australia's most coveted neighbourhoods — every listing curated for quality, location, and lasting value."}), 55: ('wagtail.blocks.CharBlock', (), {'default': 'For Sale'}), 56: ('wagtail.blocks.CharBlock', (), {'help_text': 'Path relative to public/ folder or full URL'}), 57: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 2,400', 'required': False}), 58: ('wagtail.blocks.CharBlock', (), {'help_text': 'Links to /properties/<slug>', 'required': False}), 59: ('wagtail.blocks.StructBlock', [[('title', 30), ('location', 30), ('price', 30), ('status', 55), ('image_url', 56), ('beds', 3), ('baths', 3), ('area', 57), ('property_slug', 58)]], {}), 60: ('wagtail.blocks.ListBlock', (59,), {}), 61: ('wagtail.blocks.StructBlock', [[('eyebrow', 51), ('heading', 52), ('heading_em', 53), ('subtitle', 54), ('projects', 60)]], {})}, help_text='Add sections to build the home page. Drag to reorder.')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homeherocontent',
            name='background_image_url',
            field=models.CharField(default='images/hero-rpg-brisbane.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='homeherocontent',
            name='background_poster_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='homeherocontent',
            name='background_video_url',
            field=models.CharField(blank=True, default='vids/hero-rgp.mp4', max_length=500),
        ),
        migrations.AlterField(
            model_name='homeherocontent',
            name='title_line_1',
            field=models.CharField(default='Your [gold]Dream[/gold] Home', help_text='Use [gold]…[/gold] or [amber]…[/amber] for accent colours.', max_length=200),
        ),
        migrations.AlterField(
            model_name='homeherocontent',
            name='title_line_2',
            field=models.CharField(default='[amber]Perfectly[/amber] Delivered', max_length=200),
        ),
    ]
