# Generated by Django 5.2.12 on 2026-04-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeHeroContent',
        ),
    ]
