# Generated by Django 5.2.12 on 2026-05-22 05:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('home', '0014_alter_homepage_body'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title_line_1', models.CharField(default='Get In [gold]Touch[/gold]', max_length=255)),
                ('hero_title_line_2', models.CharField(default="[amber]We're[/amber] Here", max_length=255)),
                ('hero_subtitle', models.TextField(default='Our team is ready to guide you — from first enquiry to final key.')),
                ('hero_background_image_url', models.CharField(blank=True, default='images/contact-hero.jpg', max_length=500)),
                ('hero_primary_cta_label', models.CharField(default='Call Us', max_length=100)),
                ('hero_primary_cta_href', models.CharField(default='tel:+61450009291', max_length=255)),
                ('hero_secondary_cta_label', models.CharField(default='Email Us', max_length=100)),
                ('hero_secondary_cta_href', models.CharField(default='mailto:admin@realgoldproperties.com.au', max_length=255)),
                ('contact_content', wagtail.fields.StreamField([('contact_info', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': "Let's Talk"}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Appraisal.'}), 2: ('wagtail.blocks.TextBlock', (), {'default': "Whether you're buying, selling, or investing — our advisors are ready to guide you through every step."}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Phone'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 0450 009 291'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional link: tel:, mailto:, /contact, or full URL', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('value', 4), ('href', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'Phone, email, address, or any custom contact rows.', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Office Hours'}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'All days'}), 10: ('wagtail.blocks.CharBlock', (), {'default': '09:00 – 18:00'}), 11: ('wagtail.blocks.TextBlock', (), {'default': '"Real estate is not just a transaction — it is the beginning of a life lived better."'}), 12: ('wagtail.blocks.CharBlock', (), {'default': '— Our Promise'}), 13: ('wagtail.blocks.StructBlock', [[('headline', 0), ('headline_em', 1), ('tagline', 2), ('items', 7), ('office_label', 8), ('office_days', 9), ('office_time', 10), ('quote_text', 11), ('quote_author', 12)]], {})}, help_text='Left-side contact information block.')),
                ('form_eyebrow', models.CharField(default='Begin your enquiry', max_length=120)),
                ('form_heading_line_1', models.CharField(default="Tell us what you're", max_length=255)),
                ('form_heading_line_2', models.CharField(default='looking for.', max_length=255)),
                ('form_subtitle', models.TextField(default='Fill in the details and a specialist will respond within one business day.')),
                ('form_intent_options', models.CharField(blank=True, default='Buy,Sell,Rent,Invest,Off-Plan,Valuation', help_text='Comma-separated intent chips shown above the form.', max_length=500)),
                ('form_property_type_options', models.CharField(blank=True, default='Apartment,Villa / Townhouse,Penthouse,Commercial,Plot / Land', help_text='Comma-separated property types shown in the dropdown.', max_length=600)),
                ('form_budget_min', models.PositiveIntegerField(default=500000)),
                ('form_budget_max', models.PositiveIntegerField(default=20000000)),
                ('form_budget_step', models.PositiveIntegerField(default=500000)),
                ('form_budget_default', models.PositiveIntegerField(default=5000000)),
                ('form_submit_note', models.CharField(default='We respond within one business day.', max_length=180)),
                ('hero_background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.rgpimage')),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
