# Generated by Django 5.2.12 on 2026-05-22 08:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_normalize_home_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='hero_content',
            field=wagtail.fields.StreamField([('internal_page_hero', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Get In [gold]Touch[/gold]'}), 1: ('wagtail.blocks.CharBlock', (), {'default': "[amber]We're[/amber] Here"}), 2: ('wagtail.blocks.TextBlock', (), {'default': 'Our team is ready to guide you — from first enquiry to final key.'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pick hero background image from media library.', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'images/contact-hero.jpg', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable to use the optional hero background video.', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Video path relative to public/ or full URL (used when video is enabled).', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No panel'), ('buttons', 'Buttons panel'), ('stats', 'Stats slab')], 'help_text': 'Choose whether the hero shows buttons, stats, or no panel.', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /contact), tel:/mailto:, or full URL', 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('blue', 'Blue'), ('outline', 'Outline')], 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 8), ('href', 9), ('style', 10), ('open_in_new_tab', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Used when mode is Buttons panel.', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5, 100%, 350+', 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Avg. Rating', 'required': True}), 16: ('wagtail.blocks.StructBlock', [[('value', 14), ('label', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'help_text': 'Used when mode is Stats slab.', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 1), ('subtitle', 2), ('background_image', 3), ('background_image_url', 4), ('show_video', 5), ('background_video_url', 6), ('mode', 7), ('buttons', 13), ('stats', 17)]], {})}, help_text='Reusable internal page hero block (buttons or stats mode).'),
        ),
    ]
