# Generated by Codex on 2026-05-22
import uuid

from django.db import migrations


def seed_internal_hero_from_legacy_fields(apps, schema_editor):
    ContactPage = apps.get_model("home", "ContactPage")

    for page in ContactPage.objects.all():
        if page.hero_content:
            continue

        buttons = []
        if (page.hero_primary_cta_label or "").strip():
            buttons.append(
                {
                    "type": "item",
                    "value": {
                        "label": page.hero_primary_cta_label,
                        "href": page.hero_primary_cta_href,
                        "style": "gold",
                        "open_in_new_tab": False,
                    },
                    "id": str(uuid.uuid4()),
                }
            )

        if (page.hero_secondary_cta_label or "").strip():
            buttons.append(
                {
                    "type": "item",
                    "value": {
                        "label": page.hero_secondary_cta_label,
                        "href": page.hero_secondary_cta_href,
                        "style": "blue",
                        "open_in_new_tab": False,
                    },
                    "id": str(uuid.uuid4()),
                }
            )

        hero_value = {
            "title_line_1": page.hero_title_line_1,
            "title_line_2": page.hero_title_line_2,
            "subtitle": page.hero_subtitle,
            "background_image": page.hero_background_image_id,
            "background_image_url": page.hero_background_image_url,
            "show_video": False,
            "background_video_url": "",
            "mode": "buttons" if buttons else "none",
            "buttons": buttons,
            "stats": [],
        }

        page.hero_content = [
            {
                "type": "internal_page_hero",
                "value": hero_value,
                "id": str(uuid.uuid4()),
            }
        ]
        page.save(update_fields=["hero_content"])


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_contactpage_hero_content"),
    ]

    operations = [
        migrations.RunPython(
            seed_internal_hero_from_legacy_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
