# Generated by Django 5.2.12 on 2026-05-22 10:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_seed_contactpage_internal_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='contact_content',
            field=wagtail.fields.StreamField([('contact_info', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': "Let's Talk Appraisal."}), 1: ('wagtail.blocks.TextBlock', (), {'default': "Whether you're buying, selling, or investing — our advisors are ready to guide you through every step."}), 2: ('wagtail.blocks.CharBlock', (), {'default': '0450 009 291'}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'admin@realgoldproperties.com.au'}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Forest Lake, Brisbane QLD 4078'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'All days · 09:00 – 18:00'}), 6: ('wagtail.blocks.TextBlock', (), {'default': '"Real estate is not just a transaction — it is the beginning of a life lived better."'}), 7: ('wagtail.blocks.CharBlock', (), {'default': '— Our Promise'}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('tagline', 1), ('contact_number', 2), ('email', 3), ('address', 4), ('working_hours', 5), ('quote_text', 6), ('quote_author', 7)]], {})}, help_text='Fixed contact information fields shown on the left side.', verbose_name='Contact Info'),
        ),
    ]
