# Generated by Codex on 2026-05-22
from django.db import migrations


def _legacy_value_from_items(items, candidates):
    if not isinstance(items, list):
        return ""
    normalized = {str(name).strip().lower() for name in candidates}
    for item in items:
        if not isinstance(item, dict):
            continue
        label = str(item.get("label", "")).strip().lower()
        if label in normalized:
            return str(item.get("value", "")).strip()
    return ""


def normalize_contact_info_to_fixed_fields(apps, schema_editor):
    ContactPage = apps.get_model("home", "ContactPage")

    for page in ContactPage.objects.all():
        stream_data = list(page.contact_content.stream_data or [])
        changed = False

        for block in stream_data:
            if not isinstance(block, dict) or block.get("type") != "contact_info":
                continue

            value = block.get("value")
            if not isinstance(value, dict):
                continue

            items = value.get("items")
            legacy_title = " ".join(
                part for part in [str(value.get("headline", "")).strip(), str(value.get("headline_em", "")).strip()] if part
            ).strip()
            office_days = str(value.get("office_days", "")).strip()
            office_time = str(value.get("office_time", "")).strip()

            block["value"] = {
                "title": str(value.get("title", "")).strip() or legacy_title or "Let's Talk Appraisal.",
                "tagline": str(value.get("tagline", "")).strip()
                or (
                    "Whether you're buying, selling, or investing — our advisors are ready "
                    "to guide you through every step."
                ),
                "contact_number": str(value.get("contact_number", "")).strip()
                or _legacy_value_from_items(items, {"contact number", "phone"})
                or "0450 009 291",
                "email": str(value.get("email", "")).strip()
                or _legacy_value_from_items(items, {"email"})
                or "admin@realgoldproperties.com.au",
                "address": str(value.get("address", "")).strip()
                or _legacy_value_from_items(items, {"address", "visit"})
                or "Forest Lake, Brisbane QLD 4078",
                "working_hours": str(value.get("working_hours", "")).strip()
                or " · ".join(part for part in [office_days, office_time] if part)
                or "All days · 09:00 – 18:00",
                "quote_text": str(value.get("quote_text", "")).strip()
                or (
                    '"Real estate is not just a transaction — it is the beginning of a life '
                    'lived better."'
                ),
                "quote_author": str(value.get("quote_author", "")).strip() or "— Our Promise",
            }
            changed = True

        if changed:
            page.contact_content = stream_data
            page.save(update_fields=["contact_content"])


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_contactpage_contact_content"),
    ]

    operations = [
        migrations.RunPython(
            normalize_contact_info_to_fixed_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
