# Generated by Django 5.2.12 on 2026-05-22 13:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_teampage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertiesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_content', wagtail.fields.StreamField([('internal_page_hero', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Get In [gold]Touch[/gold]'}), 1: ('wagtail.blocks.CharBlock', (), {'default': "[amber]We're[/amber] Here"}), 2: ('wagtail.blocks.TextBlock', (), {'default': 'Our team is ready to guide you — from first enquiry to final key.'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pick hero background image from media library.', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'images/contact-hero.jpg', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable to use the optional hero background video.', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Video path relative to public/ or full URL (used when video is enabled).', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No panel'), ('buttons', 'Buttons panel'), ('stats', 'Stats slab')], 'help_text': 'Choose whether the hero shows buttons, stats, or no panel.', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /contact), tel:/mailto:, or full URL', 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('blue', 'Blue'), ('outline', 'Outline')], 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 8), ('href', 9), ('style', 10), ('open_in_new_tab', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Used when mode is Buttons panel.', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5, 100%, 350+', 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Avg. Rating', 'required': True}), 16: ('wagtail.blocks.StructBlock', [[('value', 14), ('label', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'help_text': 'Used when mode is Stats slab.', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 1), ('subtitle', 2), ('background_image', 3), ('background_image_url', 4), ('show_video', 5), ('background_video_url', 6), ('mode', 7), ('buttons', 13), ('stats', 17)]], {})}, help_text='Reusable internal page hero block (buttons or stats mode).')),
                ('property_section_eyebrow', models.CharField(default='Browse Listings', max_length=120)),
                ('property_section_heading', models.CharField(default='Discover Your Next Property', max_length=255)),
                ('property_section_subtitle', models.TextField(default='Filter by sale, rent, or sold status and explore our complete listing portfolio in one place.')),
                ('marquee_eyebrow', models.CharField(default='Featured Portfolio', max_length=120)),
                ('marquee_title', models.CharField(default='Explore', max_length=255)),
                ('marquee_title_em', models.CharField(default='Premium Homes', max_length=255)),
                ('marquee_subtitle', models.TextField(default='A curated selection of standout residences from across our portfolio — updated regularly.')),
                ('marquee_cta_label', models.CharField(default='View All Properties', max_length=120)),
                ('content', wagtail.fields.StreamField([('property_cta', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Need Help Choosing?'}), 1: ('wagtail.blocks.CharBlock', (), {'default': "Let's Find Your"}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Perfect Home'}), 3: ('wagtail.blocks.TextBlock', (), {'default': "Tell us what you're looking for and we'll shortlist the best options, arrange inspections, and guide you through every step."}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /properties) or full URL', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 4), ('href', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('label', 4), ('href', 5)]], {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Data-backed guidance'}), 9: ('wagtail.blocks.StructBlock', [[('title', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': 'Optional right-column commitments.', 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Enable video background mode. When off, image background is used.', 'required': False}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image mode background. Also used as fallback if video is unavailable.', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'images/int.jpg', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'vids/cta-2-vid.mp4', 'help_text': 'Video path relative to public/ or full URL. Used when video mode is enabled.', 'required': False}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Poster image shown before video loads. Used only when video mode is enabled.', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'images/int.jpg', 'help_text': 'Fallback poster path relative to public/ or full URL.', 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'default': '100vh', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('title_em', 2), ('text', 3), ('primary', 6), ('secondary', 7), ('commitments', 10), ('use_video', 11), ('background_image', 12), ('background_image_url', 13), ('background_video_url', 14), ('video_poster_image', 15), ('video_poster_image_url', 16), ('min_height', 17)]], {})}, help_text='Add reusable content blocks for this page.')),
            ],
            options={
                'verbose_name': 'Properties Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
