# Generated by Django 5.2.12 on 2026-06-09 09:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('home', '0022_propertiespage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EoiPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_content', wagtail.fields.StreamField([('internal_page_hero', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Get In [gold]Touch[/gold]'}), 1: ('wagtail.blocks.CharBlock', (), {'default': "[amber]We're[/amber] Here"}), 2: ('wagtail.blocks.TextBlock', (), {'default': 'Our team is ready to guide you — from first enquiry to final key.'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pick hero background image from media library.', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'images/contact-hero.jpg', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable to use the optional hero background video.', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Video path relative to public/ or full URL (used when video is enabled).', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No panel'), ('buttons', 'Buttons panel'), ('stats', 'Stats slab')], 'help_text': 'Choose whether the hero shows buttons, stats, or no panel.', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /contact), tel:/mailto:, or full URL', 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('blue', 'Blue'), ('outline', 'Outline')], 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 8), ('href', 9), ('style', 10), ('open_in_new_tab', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Used when mode is Buttons panel.', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5, 100%, 350+', 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Avg. Rating', 'required': True}), 16: ('wagtail.blocks.StructBlock', [[('value', 14), ('label', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'help_text': 'Used when mode is Stats slab.', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 1), ('subtitle', 2), ('background_image', 3), ('background_image_url', 4), ('show_video', 5), ('background_video_url', 6), ('mode', 7), ('buttons', 13), ('stats', 17)]], {})}, help_text='Internal page hero block.')),
                ('legal_text', models.TextField(default='I/We acknowledge that if this offer is accepted, I/We will be required to enter into and execute a contract of sale on these terms. I/We acknowledge that we may be one of several parties making offers to the seller for their consideration. Both purchaser and seller must sign a contract of sale before this offer becomes legally binding. An offer may be withdrawn at any time before signing a contract of sale.')),
            ],
            options={
                'verbose_name': 'Expression of Interest Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TestimonialsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_content', wagtail.fields.StreamField([('internal_page_hero', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Get In [gold]Touch[/gold]'}), 1: ('wagtail.blocks.CharBlock', (), {'default': "[amber]We're[/amber] Here"}), 2: ('wagtail.blocks.TextBlock', (), {'default': 'Our team is ready to guide you — from first enquiry to final key.'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pick hero background image from media library.', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'images/contact-hero.jpg', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable to use the optional hero background video.', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Video path relative to public/ or full URL (used when video is enabled).', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No panel'), ('buttons', 'Buttons panel'), ('stats', 'Stats slab')], 'help_text': 'Choose whether the hero shows buttons, stats, or no panel.', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /contact), tel:/mailto:, or full URL', 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('blue', 'Blue'), ('outline', 'Outline')], 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 8), ('href', 9), ('style', 10), ('open_in_new_tab', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Used when mode is Buttons panel.', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5, 100%, 350+', 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Avg. Rating', 'required': True}), 16: ('wagtail.blocks.StructBlock', [[('value', 14), ('label', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'help_text': 'Used when mode is Stats slab.', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 1), ('subtitle', 2), ('background_image', 3), ('background_image_url', 4), ('show_video', 5), ('background_video_url', 6), ('mode', 7), ('buttons', 13), ('stats', 17)]], {})}, help_text='Internal page hero block.')),
                ('content', wagtail.fields.StreamField([('featured_testimonials', 0)], blank=True, block_lookup={0: ('wagtail.blocks.StructBlock', [[]], {})}, help_text="Add the 'Featured Testimonials Slider' block here to place the SplitSlider section. All active Featured Testimonial records render automatically.")),
                ('section_eyebrow', models.CharField(default='Client Voices', max_length=120)),
                ('section_heading', models.CharField(default='What Our Clients Say', max_length=255)),
                ('section_subtitle', models.TextField(default='Real experiences from real clients — every word earned, never scripted.')),
                ('final_cta_heading', models.CharField(default='Book a Free Appraisal', max_length=255)),
                ('final_cta_body', models.TextField(default='Get a clear price range, honest advice, and a plan that positions your property for a confident sale.')),
                ('final_cta_primary_label', models.CharField(default='Book Your Appraisal', max_length=120)),
                ('final_cta_primary_href', models.CharField(default='/contact', max_length=255)),
                ('final_cta_secondary_label', models.CharField(default='Talk to Rahul', max_length=120)),
                ('final_cta_secondary_href', models.CharField(default='/contact', max_length=255)),
            ],
            options={
                'verbose_name': 'Testimonials Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_content', wagtail.fields.StreamField([('internal_page_hero', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Get In [gold]Touch[/gold]'}), 1: ('wagtail.blocks.CharBlock', (), {'default': "[amber]We're[/amber] Here"}), 2: ('wagtail.blocks.TextBlock', (), {'default': 'Our team is ready to guide you — from first enquiry to final key.'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pick hero background image from media library.', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'images/contact-hero.jpg', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable to use the optional hero background video.', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Video path relative to public/ or full URL (used when video is enabled).', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No panel'), ('buttons', 'Buttons panel'), ('stats', 'Stats slab')], 'help_text': 'Choose whether the hero shows buttons, stats, or no panel.', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /contact), tel:/mailto:, or full URL', 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('blue', 'Blue'), ('outline', 'Outline')], 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 8), ('href', 9), ('style', 10), ('open_in_new_tab', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Used when mode is Buttons panel.', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5, 100%, 350+', 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Avg. Rating', 'required': True}), 16: ('wagtail.blocks.StructBlock', [[('value', 14), ('label', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'help_text': 'Used when mode is Stats slab.', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 1), ('subtitle', 2), ('background_image', 3), ('background_image_url', 4), ('show_video', 5), ('background_video_url', 6), ('mode', 7), ('buttons', 13), ('stats', 17)]], {})}, help_text='Internal page hero block.')),
                ('intro_statement', models.TextField(default='Rahul Singh is the appraisal-first agent behind Real Gold Properties — bringing local clarity, data-backed pricing, and calm negotiation to every homeowner.')),
                ('split_heading', models.CharField(default='Why Sellers Choose Rahul', max_length=255)),
                ('split_p1', models.TextField(default='He translates market noise into a clear, confident price position — with a strategy that attracts buyers and protects your upside.')),
                ('split_p2', models.TextField(default='You get straight answers, a staged plan, and weekly feedback so the appraisal never sits still.')),
                ('split_bullet_1', models.TextField(default='Street-level pricing: recent sales, buyer demand, and suburb momentum.')),
                ('split_bullet_2', models.TextField(default='Launch strategy: presentation, timing, and campaign plan that drives competition.')),
                ('split_bullet_3', models.TextField(default='Calm guidance: no pressure, just clarity and next steps.')),
                ('split_video_url', models.CharField(blank=True, default='vids/rgp-video.mp4', max_length=500)),
                ('split_cta_label', models.CharField(default='Book Your Appraisal', max_length=120)),
                ('split_cta_href', models.CharField(default='/contact', max_length=255)),
                ('overlay_heading', models.CharField(default='The Appraisal Strategy', max_length=255)),
                ('overlay_text', models.TextField(default="Rahul's appraisals are more than a number. Each one is built to attract the right buyers and set a confident path to sale.")),
                ('overlay_image_url', models.CharField(blank=True, default='images/int.jpg', max_length=500)),
                ('overlay_step_1', models.CharField(default='01 On-site walk-through + market scan', max_length=255)),
                ('overlay_step_2', models.CharField(default='02 Pricing range + demand positioning', max_length=255)),
                ('overlay_step_3', models.CharField(default='03 Launch plan + feedback loop', max_length=255)),
                ('avail_eyebrow', models.CharField(default='APPRAISAL', max_length=120)),
                ('avail_heading', models.CharField(default='Ready For Your Appraisal?', max_length=255)),
                ('avail_text', models.TextField(default="Book a free, no-pressure appraisal with Rahul Singh. You'll get a clear price range, honest advice, and a next-step plan.")),
                ('avail_image_url', models.CharField(blank=True, default='images/rahul-singh.jpg', max_length=500)),
                ('avail_cta_label', models.CharField(default='Book Your Appraisal', max_length=120)),
                ('avail_cta_href', models.CharField(default='/contact', max_length=255)),
                ('avail_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.rgpimage')),
                ('overlay_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.rgpimage')),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_content', wagtail.fields.StreamField([('internal_page_hero', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Get In [gold]Touch[/gold]'}), 1: ('wagtail.blocks.CharBlock', (), {'default': "[amber]We're[/amber] Here"}), 2: ('wagtail.blocks.TextBlock', (), {'default': 'Our team is ready to guide you — from first enquiry to final key.'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pick hero background image from media library.', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'images/contact-hero.jpg', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable to use the optional hero background video.', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Video path relative to public/ or full URL (used when video is enabled).', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No panel'), ('buttons', 'Buttons panel'), ('stats', 'Stats slab')], 'help_text': 'Choose whether the hero shows buttons, stats, or no panel.', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /contact), tel:/mailto:, or full URL', 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('blue', 'Blue'), ('outline', 'Outline')], 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 8), ('href', 9), ('style', 10), ('open_in_new_tab', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Used when mode is Buttons panel.', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5, 100%, 350+', 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Avg. Rating', 'required': True}), 16: ('wagtail.blocks.StructBlock', [[('value', 14), ('label', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'help_text': 'Used when mode is Stats slab.', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 1), ('subtitle', 2), ('background_image', 3), ('background_image_url', 4), ('show_video', 5), ('background_video_url', 6), ('mode', 7), ('buttons', 13), ('stats', 17)]], {})}, help_text='Internal page hero block.')),
                ('intro_statement', models.TextField(default='A full-service partner for buying, selling, and renting — one team, three core services, zero guesswork.')),
                ('buy_heading', models.CharField(default='Buy With Confidence From Day One', max_length=255)),
                ('buy_p1', models.TextField(default='We narrow the field quickly, secure the right property at the right price, and guide you through every step of the purchase process.')),
                ('buy_p2', models.TextField(default="From off-market access to finance coordination and settlement support — you're never navigating alone.")),
                ('buy_image_url', models.CharField(blank=True, default='images/ps1 (6).jpg', max_length=500)),
                ('buy_cta_label', models.CharField(default='Explore Our Homes', max_length=120)),
                ('buy_cta_href', models.CharField(default='/properties', max_length=255)),
                ('cta_eyebrow', models.CharField(default='Ready to Move?', max_length=120)),
                ('cta_title', models.CharField(default='Get a', max_length=255)),
                ('cta_title_em', models.CharField(default='Tailored Plan', max_length=255)),
                ('cta_text', models.TextField(default="Tell us your goal and timeline — we'll map out a strategy built around your situation.")),
                ('cta_primary_label', models.CharField(default='Book a Consultation', max_length=120)),
                ('cta_primary_href', models.CharField(default='/contact', max_length=255)),
                ('cta_secondary_label', models.CharField(default='0450 009 291', max_length=120)),
                ('cta_secondary_href', models.CharField(default='tel:+61450009291', max_length=255)),
                ('cta_stat_1_value', models.CharField(default='5+', max_length=50)),
                ('cta_stat_1_label', models.CharField(default='Years Experience', max_length=100)),
                ('cta_stat_2_value', models.CharField(default='100+', max_length=50)),
                ('cta_stat_2_label', models.CharField(default='Happy Clients', max_length=100)),
                ('cta_stat_3_value', models.CharField(default='24/7', max_length=50)),
                ('cta_stat_3_label', models.CharField(default='Support Available', max_length=100)),
                ('sell_heading', models.CharField(default='Sell With Clear Strategy', max_length=255)),
                ('sell_text', models.TextField(default="Pricing, positioning, staging, and marketing — all aligned to attract the right buyers and deliver a result you're confident in.")),
                ('sell_image_url', models.CharField(blank=True, default='images/ps1 (5).jpg', max_length=500)),
                ('sell_cta_label', models.CharField(default='Request a Valuation', max_length=120)),
                ('sell_cta_href', models.CharField(default='/contact', max_length=255)),
                ('rent_heading', models.CharField(default='Lease With Confidence', max_length=255)),
                ('rent_text', models.TextField(default='Premium leasing, tenant screening, and ongoing property care — so your investment performs without the stress.')),
                ('rent_image_url', models.CharField(blank=True, default='images/ps1 (1).jpg', max_length=500)),
                ('rent_cta_label', models.CharField(default='View Available Rentals', max_length=120)),
                ('rent_cta_href', models.CharField(default='/properties', max_length=255)),
                ('buy_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.rgpimage')),
                ('rent_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.rgpimage')),
                ('sell_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.rgpimage')),
            ],
            options={
                'verbose_name': 'Services Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
