# Generated by Django 5.2.12 on 2026-06-09 09:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_eoipage_testimonialspage_aboutpage_servicespage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialspage',
            name='content',
            field=wagtail.fields.StreamField([('featured_testimonials', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Testimonials', 'help_text': "Small label above the heading (e.g. 'Client Stories')", 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'What Our Clients Say', 'help_text': 'Main section heading'}), 2: ('wagtail.blocks.TextBlock', (), {'default': '', 'help_text': 'Optional sub-heading shown below the main heading', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('subtitle', 2)]], {})}, help_text="Add the 'Featured Testimonials Slider' block here to place the SplitSlider section. All active Featured Testimonial records render automatically."),
        ),
    ]
