# Generated by Django 5.2.12 on 2026-06-09 09:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_testimonialspage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonialspage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='testimonialspage',
            name='final_cta_body',
        ),
        migrations.RemoveField(
            model_name='testimonialspage',
            name='final_cta_heading',
        ),
        migrations.RemoveField(
            model_name='testimonialspage',
            name='final_cta_primary_href',
        ),
        migrations.RemoveField(
            model_name='testimonialspage',
            name='final_cta_primary_label',
        ),
        migrations.RemoveField(
            model_name='testimonialspage',
            name='final_cta_secondary_href',
        ),
        migrations.RemoveField(
            model_name='testimonialspage',
            name='final_cta_secondary_label',
        ),
        migrations.RemoveField(
            model_name='testimonialspage',
            name='hero_content',
        ),
        migrations.RemoveField(
            model_name='testimonialspage',
            name='section_eyebrow',
        ),
        migrations.RemoveField(
            model_name='testimonialspage',
            name='section_heading',
        ),
        migrations.RemoveField(
            model_name='testimonialspage',
            name='section_subtitle',
        ),
        migrations.AddField(
            model_name='testimonialspage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 18), ('featured_testimonials', 22), ('text_testimonials_grid', 26), ('ticker', 27), ('final_cta', 33)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Get In [gold]Touch[/gold]'}), 1: ('wagtail.blocks.CharBlock', (), {'default': "[amber]We're[/amber] Here"}), 2: ('wagtail.blocks.TextBlock', (), {'default': 'Our team is ready to guide you — from first enquiry to final key.'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pick hero background image from media library.', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'images/contact-hero.jpg', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable to use the optional hero background video.', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Video path relative to public/ or full URL (used when video is enabled).', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No panel'), ('buttons', 'Buttons panel'), ('stats', 'Stats slab')], 'help_text': 'Choose whether the hero shows buttons, stats, or no panel.', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /contact), tel:/mailto:, or full URL', 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('blue', 'Blue'), ('outline', 'Outline')], 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 8), ('href', 9), ('style', 10), ('open_in_new_tab', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Used when mode is Buttons panel.', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5, 100%, 350+', 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Avg. Rating', 'required': True}), 16: ('wagtail.blocks.StructBlock', [[('value', 14), ('label', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'help_text': 'Used when mode is Stats slab.', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 1), ('subtitle', 2), ('background_image', 3), ('background_image_url', 4), ('show_video', 5), ('background_video_url', 6), ('mode', 7), ('buttons', 13), ('stats', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'Testimonials', 'help_text': "Small label above the heading (e.g. 'Client Stories')", 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'What Our Clients Say', 'help_text': 'Main section heading'}), 21: ('wagtail.blocks.TextBlock', (), {'default': '', 'help_text': 'Optional sub-heading shown below the main heading', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('eyebrow', 19), ('heading', 20), ('subtitle', 21)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'Client Voices', 'required': False}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'What Our Clients Say'}), 25: ('wagtail.blocks.TextBlock', (), {'default': 'Real experiences from real clients — every word earned, never scripted.', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('eyebrow', 23), ('heading', 24), ('subtitle', 25)]], {}), 27: ('wagtail.blocks.StructBlock', [[]], {}), 28: ('wagtail.blocks.CharBlock', (), {'default': 'Book a Free Appraisal'}), 29: ('wagtail.blocks.TextBlock', (), {'default': 'Get a clear price range, honest advice, and a plan that positions your property for a confident sale.'}), 30: ('wagtail.blocks.CharBlock', (), {'default': 'Book Your Appraisal'}), 31: ('wagtail.blocks.CharBlock', (), {'default': '/contact', 'required': False}), 32: ('wagtail.blocks.CharBlock', (), {'default': 'Talk to Rahul'}), 33: ('wagtail.blocks.StructBlock', [[('heading', 28), ('body', 29), ('primary_label', 30), ('primary_href', 31), ('secondary_label', 32), ('secondary_href', 31)]], {})}, help_text='Add, remove and reorder sections. Each block is a section on the testimonials page.'),
        ),
    ]
