# Generated by Django 5.2.12 on 2026-06-09 10:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_testimonialspage_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='avail_cta_href',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='avail_cta_label',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='avail_eyebrow',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='avail_heading',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='avail_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='avail_image_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='avail_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_content',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='intro_statement',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='overlay_heading',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='overlay_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='overlay_image_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='overlay_step_1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='overlay_step_2',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='overlay_step_3',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='overlay_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='split_bullet_1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='split_bullet_2',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='split_bullet_3',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='split_cta_href',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='split_cta_label',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='split_heading',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='split_p1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='split_p2',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='split_video_url',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 17), ('intro', 19), ('split', 28), ('overlay', 34), ('avail', 40)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': ''}), 1: ('wagtail.blocks.TextBlock', (), {'default': ''}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pick hero background image from media library.', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable to use the optional hero background video.', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Video path relative to public/ or full URL (used when video is enabled).', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No panel'), ('buttons', 'Buttons panel'), ('stats', 'Stats slab')], 'help_text': 'Choose whether the hero shows buttons, stats, or no panel.', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /contact), tel:/mailto:, or full URL', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('blue', 'Blue'), ('outline', 'Outline')], 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('label', 7), ('href', 8), ('style', 9), ('open_in_new_tab', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Used when mode is Buttons panel.', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5, 100%, 350+', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Avg. Rating', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('value', 13), ('label', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Used when mode is Stats slab.', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 0), ('subtitle', 1), ('background_image', 2), ('background_image_url', 3), ('show_video', 4), ('background_video_url', 5), ('mode', 6), ('buttons', 12), ('stats', 16)]], {}), 18: ('wagtail.blocks.TextBlock', (), {'default': 'Rahul Singh is the appraisal-first agent behind Real Gold Properties — bringing local clarity, data-backed pricing, and calm negotiation to every homeowner.'}), 19: ('wagtail.blocks.StructBlock', [[('statement', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'Why Sellers Choose Rahul'}), 21: ('wagtail.blocks.TextBlock', (), {'default': 'He translates market noise into a clear, confident price position — with a strategy that attracts buyers and protects your upside.'}), 22: ('wagtail.blocks.TextBlock', (), {'default': 'You get straight answers, a staged plan, and weekly feedback so the appraisal never sits still.'}), 23: ('wagtail.blocks.CharBlock', (), {}), 24: ('wagtail.blocks.ListBlock', (23,), {'help_text': 'Key selling points shown as a bullet list.'}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'vids/rgp-video.mp4', 'help_text': 'Path relative to public/ or full URL.', 'required': False}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'Book Your Appraisal'}), 27: ('wagtail.blocks.CharBlock', (), {'default': '/contact', 'required': False}), 28: ('wagtail.blocks.StructBlock', [[('heading', 20), ('p1', 21), ('p2', 22), ('bullets', 24), ('video_url', 25), ('cta_label', 26), ('cta_href', 27)]], {}), 29: ('wagtail.blocks.CharBlock', (), {'default': 'The Appraisal Strategy'}), 30: ('wagtail.blocks.TextBlock', (), {'default': "Rahul's appraisals are more than a number. Each one is built to attract the right buyers and set a confident path to sale."}), 31: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Overlay background image. Takes priority over the URL field.', 'required': False}), 32: ('wagtail.blocks.CharBlock', (), {'default': 'images/int.jpg', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 33: ('wagtail.blocks.ListBlock', (23,), {'help_text': 'Numbered process steps shown in the overlay card.'}), 34: ('wagtail.blocks.StructBlock', [[('heading', 29), ('text', 30), ('image', 31), ('image_url', 32), ('steps', 33)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'default': 'APPRAISAL', 'required': False}), 36: ('wagtail.blocks.CharBlock', (), {'default': 'Ready For Your Appraisal?'}), 37: ('wagtail.blocks.TextBlock', (), {'default': "Book a free, no-pressure appraisal with Rahul Singh. You'll get a clear price range, honest advice, and a next-step plan."}), 38: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Section photo. Takes priority over the URL field.', 'required': False}), 39: ('wagtail.blocks.CharBlock', (), {'default': 'images/rahul-singh.jpg', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 40: ('wagtail.blocks.StructBlock', [[('eyebrow', 35), ('heading', 36), ('text', 37), ('image', 38), ('image_url', 39), ('cta_label', 26), ('cta_href', 27)]], {})}, help_text='Add, remove and reorder sections. Each block is a section on the about page.'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='hero_content',
            field=wagtail.fields.StreamField([('internal_page_hero', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': ''}), 1: ('wagtail.blocks.TextBlock', (), {'default': ''}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pick hero background image from media library.', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable to use the optional hero background video.', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Video path relative to public/ or full URL (used when video is enabled).', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No panel'), ('buttons', 'Buttons panel'), ('stats', 'Stats slab')], 'help_text': 'Choose whether the hero shows buttons, stats, or no panel.', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /contact), tel:/mailto:, or full URL', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('blue', 'Blue'), ('outline', 'Outline')], 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('label', 7), ('href', 8), ('style', 9), ('open_in_new_tab', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Used when mode is Buttons panel.', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5, 100%, 350+', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Avg. Rating', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('value', 13), ('label', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Used when mode is Stats slab.', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 0), ('subtitle', 1), ('background_image', 2), ('background_image_url', 3), ('show_video', 4), ('background_video_url', 5), ('mode', 6), ('buttons', 12), ('stats', 16)]], {})}, help_text='Reusable internal page hero block (buttons or stats mode).'),
        ),
        migrations.AlterField(
            model_name='eoipage',
            name='hero_content',
            field=wagtail.fields.StreamField([('internal_page_hero', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': ''}), 1: ('wagtail.blocks.TextBlock', (), {'default': ''}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pick hero background image from media library.', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable to use the optional hero background video.', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Video path relative to public/ or full URL (used when video is enabled).', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No panel'), ('buttons', 'Buttons panel'), ('stats', 'Stats slab')], 'help_text': 'Choose whether the hero shows buttons, stats, or no panel.', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /contact), tel:/mailto:, or full URL', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('blue', 'Blue'), ('outline', 'Outline')], 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('label', 7), ('href', 8), ('style', 9), ('open_in_new_tab', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Used when mode is Buttons panel.', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5, 100%, 350+', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Avg. Rating', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('value', 13), ('label', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Used when mode is Stats slab.', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 0), ('subtitle', 1), ('background_image', 2), ('background_image_url', 3), ('show_video', 4), ('background_video_url', 5), ('mode', 6), ('buttons', 12), ('stats', 16)]], {})}, help_text='Internal page hero block.'),
        ),
        migrations.AlterField(
            model_name='propertiespage',
            name='hero_content',
            field=wagtail.fields.StreamField([('internal_page_hero', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': ''}), 1: ('wagtail.blocks.TextBlock', (), {'default': ''}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pick hero background image from media library.', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable to use the optional hero background video.', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Video path relative to public/ or full URL (used when video is enabled).', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No panel'), ('buttons', 'Buttons panel'), ('stats', 'Stats slab')], 'help_text': 'Choose whether the hero shows buttons, stats, or no panel.', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /contact), tel:/mailto:, or full URL', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('blue', 'Blue'), ('outline', 'Outline')], 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('label', 7), ('href', 8), ('style', 9), ('open_in_new_tab', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Used when mode is Buttons panel.', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5, 100%, 350+', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Avg. Rating', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('value', 13), ('label', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Used when mode is Stats slab.', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 0), ('subtitle', 1), ('background_image', 2), ('background_image_url', 3), ('show_video', 4), ('background_video_url', 5), ('mode', 6), ('buttons', 12), ('stats', 16)]], {})}, help_text='Reusable internal page hero block (buttons or stats mode).'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='hero_content',
            field=wagtail.fields.StreamField([('internal_page_hero', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': ''}), 1: ('wagtail.blocks.TextBlock', (), {'default': ''}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pick hero background image from media library.', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable to use the optional hero background video.', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Video path relative to public/ or full URL (used when video is enabled).', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No panel'), ('buttons', 'Buttons panel'), ('stats', 'Stats slab')], 'help_text': 'Choose whether the hero shows buttons, stats, or no panel.', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /contact), tel:/mailto:, or full URL', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('blue', 'Blue'), ('outline', 'Outline')], 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('label', 7), ('href', 8), ('style', 9), ('open_in_new_tab', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Used when mode is Buttons panel.', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5, 100%, 350+', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Avg. Rating', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('value', 13), ('label', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Used when mode is Stats slab.', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 0), ('subtitle', 1), ('background_image', 2), ('background_image_url', 3), ('show_video', 4), ('background_video_url', 5), ('mode', 6), ('buttons', 12), ('stats', 16)]], {})}, help_text='Internal page hero block.'),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='hero_content',
            field=wagtail.fields.StreamField([('internal_page_hero', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': ''}), 1: ('wagtail.blocks.TextBlock', (), {'default': ''}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pick hero background image from media library.', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable to use the optional hero background video.', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Video path relative to public/ or full URL (used when video is enabled).', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No panel'), ('buttons', 'Buttons panel'), ('stats', 'Stats slab')], 'help_text': 'Choose whether the hero shows buttons, stats, or no panel.', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /contact), tel:/mailto:, or full URL', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('blue', 'Blue'), ('outline', 'Outline')], 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('label', 7), ('href', 8), ('style', 9), ('open_in_new_tab', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Used when mode is Buttons panel.', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5, 100%, 350+', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Avg. Rating', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('value', 13), ('label', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Used when mode is Stats slab.', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 0), ('subtitle', 1), ('background_image', 2), ('background_image_url', 3), ('show_video', 4), ('background_video_url', 5), ('mode', 6), ('buttons', 12), ('stats', 16)]], {})}, help_text='Reusable internal page hero block (buttons or stats mode).'),
        ),
        migrations.AlterField(
            model_name='testimonialspage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 17), ('featured_testimonials', 21), ('text_testimonials_grid', 25), ('ticker', 26), ('final_cta', 32)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': ''}), 1: ('wagtail.blocks.TextBlock', (), {'default': ''}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pick hero background image from media library.', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable to use the optional hero background video.', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Video path relative to public/ or full URL (used when video is enabled).', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No panel'), ('buttons', 'Buttons panel'), ('stats', 'Stats slab')], 'help_text': 'Choose whether the hero shows buttons, stats, or no panel.', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /contact), tel:/mailto:, or full URL', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('blue', 'Blue'), ('outline', 'Outline')], 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('label', 7), ('href', 8), ('style', 9), ('open_in_new_tab', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Used when mode is Buttons panel.', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5, 100%, 350+', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Avg. Rating', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('value', 13), ('label', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Used when mode is Stats slab.', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 0), ('subtitle', 1), ('background_image', 2), ('background_image_url', 3), ('show_video', 4), ('background_video_url', 5), ('mode', 6), ('buttons', 12), ('stats', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Testimonials', 'help_text': "Small label above the heading (e.g. 'Client Stories')", 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'What Our Clients Say', 'help_text': 'Main section heading'}), 20: ('wagtail.blocks.TextBlock', (), {'default': '', 'help_text': 'Optional sub-heading shown below the main heading', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('eyebrow', 18), ('heading', 19), ('subtitle', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'Client Voices', 'required': False}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'What Our Clients Say'}), 24: ('wagtail.blocks.TextBlock', (), {'default': 'Real experiences from real clients — every word earned, never scripted.', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('eyebrow', 22), ('heading', 23), ('subtitle', 24)]], {}), 26: ('wagtail.blocks.StructBlock', [[]], {}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'Book a Free Appraisal'}), 28: ('wagtail.blocks.TextBlock', (), {'default': 'Get a clear price range, honest advice, and a plan that positions your property for a confident sale.'}), 29: ('wagtail.blocks.CharBlock', (), {'default': 'Book Your Appraisal'}), 30: ('wagtail.blocks.CharBlock', (), {'default': '/contact', 'required': False}), 31: ('wagtail.blocks.CharBlock', (), {'default': 'Talk to Rahul'}), 32: ('wagtail.blocks.StructBlock', [[('heading', 27), ('body', 28), ('primary_label', 29), ('primary_href', 30), ('secondary_label', 31), ('secondary_href', 30)]], {})}, help_text='Add, remove and reorder sections. Each block is a section on the testimonials page.'),
        ),
    ]
