# Generated by Django 5.2.12 on 2026-06-09 10:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_aboutpage_avail_cta_href_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampage',
            name='hero_content',
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='team_section_eyebrow',
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='team_section_subtitle',
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='team_section_title_line_1',
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='team_section_title_line_2',
        ),
        migrations.AddField(
            model_name='teampage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 17), ('team_section', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': ''}), 1: ('wagtail.blocks.TextBlock', (), {'default': ''}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pick hero background image from media library.', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Fallback image path relative to public/ or full URL.', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Enable to use the optional hero background video.', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Video path relative to public/ or full URL (used when video is enabled).', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No panel'), ('buttons', 'Buttons panel'), ('stats', 'Stats slab')], 'help_text': 'Choose whether the hero shows buttons, stats, or no panel.', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Relative path (e.g. /contact), tel:/mailto:, or full URL', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('blue', 'Blue'), ('outline', 'Outline')], 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('label', 7), ('href', 8), ('style', 9), ('open_in_new_tab', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Used when mode is Buttons panel.', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5, 100%, 350+', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Avg. Rating', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('value', 13), ('label', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Used when mode is Stats slab.', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 0), ('subtitle', 1), ('background_image', 2), ('background_image_url', 3), ('show_video', 4), ('background_video_url', 5), ('mode', 6), ('buttons', 12), ('stats', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Our People', 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'The Minds'}), 20: ('wagtail.blocks.CharBlock', (), {'default': '[gold]Behind[/gold] Every Deal'}), 21: ('wagtail.blocks.TextBlock', (), {'default': 'A curated ensemble of creative minds and industry veterans — each bringing unmatched expertise to every client engagement.'}), 22: ('wagtail.blocks.StructBlock', [[('eyebrow', 18), ('title_line_1', 19), ('title_line_2', 20), ('subtitle', 21)]], {})}, help_text='Add, remove and reorder sections. Team members always come from the Team Member snippets.'),
        ),
    ]
