"""
Data migration: convert any RichText HTML stored in title_line_1 / title_line_2
back to the [gold]…[/gold] token format used by CharBlock.

Schema AlterField operations are recorded in 0032 (generated by makemigrations).
"""
import re

from django.db import migrations


# ─── Conversion helpers ───────────────────────────────────────────────────────

def _html_to_tokens(text):
    if not isinstance(text, str) or not text.strip().startswith("<"):
        return text
    inner = re.sub(r"^<p[^>]*>", "", text.strip())
    inner = re.sub(r"</p>$", "", inner.strip())
    inner = re.sub(r'<span[^>]*class="rg-gold"[^>]*>(.*?)</span>', r'[gold]\1[/gold]', inner)
    inner = re.sub(r'<span[^>]*class="rg-amber"[^>]*>(.*?)</span>', r'[amber]\1[/amber]', inner)
    inner = re.sub(r"<[^>]+>", "", inner)
    return inner.strip()


def _patch_blocks(stream_data, block_types_fields):
    changed = False
    if not isinstance(stream_data, list):
        return False
    for block in stream_data:
        btype = block.get("type")
        fields = block_types_fields.get(btype)
        if not fields:
            continue
        value = block.get("value")
        if not isinstance(value, dict):
            continue
        for field in fields:
            old = value.get(field, "")
            if isinstance(old, str) and old.strip().startswith("<"):
                value[field] = _html_to_tokens(old)
                changed = True
    return changed


def forwards(apps, schema_editor):
    TITLE_FIELDS = ["title_line_1", "title_line_2"]

    for page in apps.get_model("home", "HomePage").objects.all():
        if _patch_blocks(page.body, {"hero": TITLE_FIELDS}):
            page.save(update_fields=["body"])

    for page in apps.get_model("home", "TeamPage").objects.all():
        if _patch_blocks(page.body, {"hero": TITLE_FIELDS, "team_section": TITLE_FIELDS}):
            page.save(update_fields=["body"])

    for model_name in ("AboutPage", "ContactPage", "TestimonialsPage", "PropertiesPage"):
        for page in apps.get_model("home", model_name).objects.all():
            if _patch_blocks(page.body, {"hero": TITLE_FIELDS}):
                page.save(update_fields=["body"])

    for model_name in ("ServicesPage", "EoiPage"):
        for page in apps.get_model("home", model_name).objects.all():
            if _patch_blocks(page.hero_content, {"internal_page_hero": TITLE_FIELDS}):
                page.save(update_fields=["hero_content"])


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_richtext_title_fields"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
