# Generated by Django 5.2.15 on 2026-06-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_aboutpage_body_alter_contactpage_body_and_more'),
        ('home', '0032_alter_block_schema_state'),
    ]

    operations = [
    ]
