# Generated by Django 5.2.15 on 2026-06-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_aboutpage_body_alter_contactpage_body_and_more'),
        ('home', '0043_alter_aboutpage_body_alter_propertiespage_body_and_more'),
    ]

    operations = [
    ]
