# Generated by Django 5.2.15 on 2026-07-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_aboutpage_body_alter_contactpage_body_and_more'),
        ('home', '0045_alter_homepage_body'),
    ]

    operations = [
    ]
