# Generated by Django 5.2.12 on 2026-05-22 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique slug for this team member.', max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(default='Property Specialist', max_length=220)),
                ('bio', models.TextField(blank=True, default='')),
                ('portrait_image_url', models.CharField(blank=True, default='', help_text='Fallback image path (e.g. images/team3.png) or full URL.', max_length=500)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=60)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated tags (e.g. Luxury Estates, Market Analysis).', max_length=500)),
                ('stat_1_value', models.CharField(blank=True, default='5+', max_length=60)),
                ('stat_1_label', models.CharField(blank=True, default='Years', max_length=80)),
                ('stat_2_value', models.CharField(blank=True, default='$120M', max_length=60)),
                ('stat_2_label', models.CharField(blank=True, default='Volume', max_length=80)),
                ('stat_3_value', models.CharField(blank=True, default='80+', max_length=60)),
                ('stat_3_label', models.CharField(blank=True, default='Properties', max_length=80)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers render first (set founder to 0).')),
                ('is_active', models.BooleanField(default=True, help_text='Only active members are sent to frontend.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portrait_image', models.ForeignKey(blank=True, help_text='Preferred team card image from media library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.rgpimage')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ('order', 'id'),
            },
        ),
    ]
